apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-frontend
spec:
  replicas: 4

  selector:
    matchLabels:
      app: swiggy-frontend

  template:
    metadata:
      labels:
        app: swiggy-frontend

    spec:
      containers:
        - name: swiggy-frontend

          image: 051299608149.dkr.ecr.ap-south-1.amazonaws.com/swiggy-clone:latest

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"